const categories=['Aleatório','Catecismo','Vida dos Santos','História','FSSPX','Quem disse essa frase?'];
const icons=['✦','✝','♙','⌛','⚜','❝'];
const state={mode:10,category:0,round:[],index:0,score:0,answered:false};
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];

$$('[data-category-options]').forEach((container,group)=>{container.innerHTML=categories.map((name,index)=>`<label><input type="radio" name="category-${group}" value="${index}" ${index===0?'checked':''}><span>${icons[index]}&nbsp; ${name}</span></label>`).join('')});
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function showScreen(name){$$('.screen').forEach(el=>el.classList.toggle('active',el.dataset.screen===name));window.scrollTo({top:0,behavior:'smooth'})}
function syncSettings(source){const scope=source.closest('.side-panel')?'.side-panel':'.home-screen';state.mode=Number($(`input[name^="mode"]:checked`,$(scope)).value);state.category=Number($(`input[name^="category-"]:checked`,$(scope)).value);$$('input[name^="mode-"] , input[name="mode"]').forEach(input=>input.checked=Number(input.value)===state.mode);$$('input[name^="category-"]').forEach(input=>input.checked=Number(input.value)===state.category)}
function startGame(event){syncSettings(event.currentTarget);const pool=state.category===0?window.QUIZ_QUESTIONS:window.QUIZ_QUESTIONS.filter(q=>q.category===state.category-1);state.round=shuffle(pool).slice(0,state.mode);state.index=0;state.score=0;closeMenu();showScreen('quiz');renderQuestion()}
function renderQuestion(){state.answered=false;const item=state.round[state.index];$('.question-count').textContent=`Pergunta ${state.index+1} de ${state.round.length}`;$('.score-live').textContent=`${state.score} acerto${state.score===1?'':'s'}`;$('.progress-track span').style.width=`${(state.index/state.round.length)*100}%`;$('.question-category').textContent=item.categoryName;$('.question-text').textContent=item.question;$('.feedback').textContent='';$('.feedback').className='feedback';$('.next-button').hidden=true;const options=shuffle(item.options.map((text,index)=>({text,correct:index===0})));$('.answers').innerHTML=options.map((option,index)=>`<button class="answer" type="button" data-correct="${option.correct}"><span class="answer-letter">${'ABCD'[index]}</span><span>${option.text}</span></button>`).join('');$$('.answer').forEach(button=>button.addEventListener('click',answerQuestion))}
function answerQuestion(event){if(state.answered)return;state.answered=true;const chosen=event.currentTarget;const correct=chosen.dataset.correct==='true';if(correct)state.score++;$$('.answer').forEach(button=>{button.disabled=true;if(button.dataset.correct==='true')button.classList.add('correct')});if(!correct)chosen.classList.add('wrong');const feedback=$('.feedback');feedback.textContent=correct?'Correto! Muito bem.':'Não foi dessa vez. A resposta correta está destacada.';feedback.classList.add(correct?'good':'bad');$('.score-live').textContent=`${state.score} acerto${state.score===1?'':'s'}`;$('.next-button').hidden=false;$('.next-button').textContent=state.index===state.round.length-1?'Ver resultado →':'Próxima pergunta →';$('.next-button').focus()}
function nextQuestion(){state.index++;if(state.index<state.round.length){renderQuestion();return}showResult()}
function showResult(){showScreen('result');const ratio=state.score/state.round.length;$('.result-title').textContent=ratio>=.9?'Resultado excelente!':ratio>=.7?'Você foi muito bem!':ratio>=.5?'Boa partida!':'Vale tentar mais uma vez!';$('.result-score strong').textContent=`${state.score}/${state.round.length}`;$('.result-message').textContent=ratio>=.7?'Seu conhecimento brilhou nesta edição. Que tal desafiar alguém da família?':'Cada partida é uma oportunidade de aprender e guardar algo novo.'}
function openMenu(){const panel=$('.side-panel');panel.classList.add('open');$('.scrim').hidden=false;$('.menu-button').setAttribute('aria-expanded','true')}
function closeMenu(){$('.side-panel').classList.remove('open');$('.scrim').hidden=true;$('.menu-button').setAttribute('aria-expanded','false')}
$$('.home-start,.side-start').forEach(button=>button.addEventListener('click',startGame));$('.next-button').addEventListener('click',nextQuestion);$('.retry-button').addEventListener('click',()=>showScreen('home'));$('.quit-button').addEventListener('click',()=>{if(confirm('Deseja encerrar esta partida?'))showScreen('home')});$('.menu-button').addEventListener('click',openMenu);$('.close-menu').addEventListener('click',closeMenu);$('.scrim').addEventListener('click',closeMenu);$('.share-button').addEventListener('click',async()=>{const text=`Fiz ${state.score}/${state.round.length} no Quizz Festa de São Pio X! Você consegue superar? ${location.href}`;if(navigator.share)await navigator.share({title:document.title,text});else{await navigator.clipboard.writeText(text);$('.share-button').textContent='Resultado copiado!'}});
