const categories=['Aleatório','Catecismo','Vida dos Santos','História','FSSPX','Quem disse essa frase?'];
const icons=['✦','✝','♙','⌛','⚜','❝'];
const state={mode:10,category:0,round:[],index:0,score:0,answered:false};
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
$$('[data-category-options]').forEach((container,group)=>{container.innerHTML=categories.map((name,index)=>`<label><input type="radio" name="category-${group}" value="${index}" ${index===0?'checked':''}><span><b class="category-icon" aria-hidden="true">${icons[index]}</b>${name}</span></label>`).join('')});
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function showScreen(name){$$('.screen').forEach(el=>el.classList.toggle('active',el.dataset.screen===name));window.scrollTo({top:0,behavior:'smooth'})}
function goHome(event){if(event)event.preventDefault();showScreen('home')}
function startGame(){state.mode=Number($('input[name="mode"]:checked').value);state.category=Number($('input[name^="category-"]:checked').value);const pool=state.category===0?window.QUIZ_QUESTIONS:window.QUIZ_QUESTIONS.filter(question=>question.category===state.category-1);state.round=shuffle(pool).slice(0,state.mode);state.index=0;state.score=0;showScreen('quiz');renderQuestion()}
function renderQuestion(){state.answered=false;const item=state.round[state.index];const progress=Math.round((state.index/state.round.length)*100);$('.question-count').textContent=`Pergunta ${state.index+1} de ${state.round.length}`;$('.score-live').textContent=`${state.score}/${state.round.length}`;$('.progress-track span').style.transform=`scaleX(${progress/100})`;$('.progress-track').setAttribute('aria-valuenow',progress);$('.question-category').textContent=item.categoryName;$('.question-text').textContent=item.question;$('.feedback').textContent='';$('.feedback').className='feedback';$('.next-button').hidden=true;const options=shuffle(item.options.map((text,index)=>({text,correct:index===0})));$('.answers').innerHTML=options.map((option,index)=>`<button class="answer" type="button" data-correct="${option.correct}"><span class="answer-letter">${'ABCD'[index]}</span><span>${option.text}</span></button>`).join('');$$('.answer').forEach(button=>button.addEventListener('click',answerQuestion))}
function answerQuestion(event){if(state.answered)return;state.answered=true;const chosen=event.currentTarget;const correct=chosen.dataset.correct==='true';if(correct)state.score++;$$('.answer').forEach(button=>{button.disabled=true;if(button.dataset.correct==='true')button.classList.add('correct')});if(!correct)chosen.classList.add('wrong');const feedback=$('.feedback');feedback.textContent=correct?'Correto! Muito bem.':'Não foi dessa vez. A resposta correta está destacada.';feedback.classList.add(correct?'good':'bad');const progress=Math.round(((state.index+1)/state.round.length)*100);$('.progress-track span').style.transform=`scaleX(${progress/100})`;$('.progress-track').setAttribute('aria-valuenow',progress);const scoreLive=$('.score-live');scoreLive.textContent=`${state.score}/${state.round.length}`;scoreLive.classList.remove('bump');void scoreLive.offsetWidth;scoreLive.classList.add('bump');$('.next-button').hidden=false;$('.next-button').textContent=state.index===state.round.length-1?'Ver resultado →':'Próxima pergunta →';$('.next-button').focus()}
function nextQuestion(){state.index++;if(state.index<state.round.length){renderQuestion();return}showResult()}
function showResult(){showScreen('result');const ratio=state.score/state.round.length;const percent=Math.round(ratio*100);let title;let message;if(ratio>=.9){title='Excelente resultado!';message=`Você acertou ${percent}% das perguntas e demonstrou grande conhecimento. Está entre os destaques desta edição.`}else if(ratio>=.7){title='Você foi muito bem!';message=`Com ${percent}% de acertos, seu desempenho foi muito bom. Mais uma partida pode levar você à pontuação máxima.`}else if(ratio>=.5){title='Bom resultado!';message=`Você acertou ${percent}% das perguntas. Há uma boa base de conhecimento e espaço para avançar ainda mais.`}else{title='Continue aprendendo!';message=`Você acertou ${percent}% das perguntas. Tente novamente: cada rodada ajuda a conhecer melhor a fé e a tradição da Igreja.`}$('.result-title').textContent=title;$('.result-score strong').textContent=`${state.score}/${state.round.length}`;$('.result-message').textContent=message}
$('.home-start').addEventListener('click',startGame);$('.brand').addEventListener('click',goHome);$('.next-button').addEventListener('click',nextQuestion);$('.retry-button').addEventListener('click',goHome);$('.quit-button').addEventListener('click',()=>{if(confirm('Deseja encerrar esta partida?'))goHome()});$('.share-button').addEventListener('click',async()=>{const button=$('.share-button');const text=`Fiz ${state.score}/${state.round.length} no Quizz Festa de São Pio X! Você consegue superar? ${location.href}`;try{if(navigator.share)await navigator.share({title:document.title,text});else{await navigator.clipboard.writeText(text);button.textContent='Resultado copiado!'}}catch(error){if(error.name!=='AbortError')button.textContent='Não foi possível compartilhar'}});
